steps:
  - label: "Build"
    plugins:
      docker#v3.8.0:
        image: "python:3.12.1-alpine3.19"
        workdir: "/workdir"
        commands:
          - "python -m py_compile sources/add2vals.py sources/calc.py"
          - "tar cvfz compiled-results.tar.gz sources/*.py*"
    artifacts:
    - "compiled-results.tar.gz"

  - label: "Test"
    plugins:
      docker#v3.8.0:
        image: "qnib/pytest"
        workdir: "/workdir"
        commands:
          - "py.test --junit-xml test-reports/results.xml sources/test_calc.py"
    artifacts:
     - "test-reports/results.xml"

  - label: "Deliver"
    plugins:
      docker#v3.8.0:
        image: "cdrx/pyinstaller-linux:python2"
        workdir: "/workdir"
        commands:
          - "tar xvfz compiled-results.tar.gz"
          - "docker run --rm -v $(pwd)/sources:/src ${IMAGE} 'pyinstaller -F add2vals.py'"
    artifacts:
      - "sources/dist/add2vals/**/*"
