# Buildkite pipeline
steps:
  - label: ":construction_worker: Build"
    command: "python -m py_compile sources/add2vals.py sources/calc.py"
    plugins:
      - docker#v3.8.0:
          image: "python:3.12.1-alpine3.19"
          always_pull: true
          workdir: "/workdir"
    artifact_paths: "sources/*.py*"
  - wait

  - label: ":white_check_mark: Test"
    command: "py.test --junit-xml test-reports/results.xml sources/test_calc.py"
    plugins:
      - docker#v3.8.0:
          image: "qnib/pytest"
          always_pull: true
          workdir: "/workdir"
  - wait

  - label: ":rocket: Deliver"
    command: 
      - 'mkdir -p ${BUILDKITE_BUILD_ID}'
      - 'buildkite-agent artifact download "sources/*.py*" ${BUILDKITE_BUILD_ID}'
      - 'docker run --rm -v $(pwd)/sources:/src cdrx/pyinstaller-linux:python2 "pyinstaller -F add2vals.py"'
      - 'docker run --rm -v $(pwd)/sources:/src cdrx/pyinstaller-linux:python2 "rm -rf build dist"'
    plugins:
      - docker#v3.8.0:
        image: "python:3.12.1-alpine3.19"
        always_pull: true
        workdir: "/workdir"
    env:
      VOLUME: '$(pwd)/sources:/src'
      IMAGE: 'cdrx/pyinstaller-linux:python2'
    artifact_paths:
      - "${BUILDKITE_BUILD_ID}/sources/dist/add2vals"
