steps:
  - label: ':construction_worker: Build'
    command: 'python -m py_compile sources/add2vals.py sources/calc.py && tar cvfz compiled-results.tar.gz sources/*.py* && ls'
    key: 'build'
    plugins:
      - docker:
          image: 'python:3.12.1-alpine3.19'
          workdir: '/workdir'
    artifacts:
      - 'compiled-results.tar.gz'

  - label: ':white_check_mark: Test'
    command: 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
    key: 'test'
    plugins:
      - docker:
          image: 'qnib/pytest'
          workdir: '/workdir'
    artifacts:
      - 'test-reports/results.xml'

  - label: ':rocket: Deliver'
    command: 'tar xvfz compiled-results.tar.gz && docker run --rm -v $(pwd)/sources:/src ${IMAGE} 'pyinstaller -F add2vals.py''
    key: 'deliver'
    plugins:
      docker:
        image: 'cdrx/pyinstaller-linux:python2'
        workdir: '/workdir'
    artifacts:
      - 'sources/dist/add2vals/**/*'
